### ISSUE TITLE
Can't use external resources with openui5_connect task

### ISSUE THREAD

**Issue by js1972** [SAP/grunt-openui5#12]
If I'm developing using resources from https://openui5.hana.ondemand.com/resources/sap-ui-core.js the openui5_connect tasks seems to block them. It only works for me when I specify a local directory for the UI5 resources... (such as when using the downloaded bower library files)?

**Comment by petermuessig** [comment]
Do you want to use the connect server acting as proxy to openui5.hana.ondemand.com?

**Comment by js1972** [comment]
I'm just trying to learn these tools better. I've been using the connect server on its own for a while now and you simply specify the base option as "." to set your web root. 
It will then serve your app with the ui5 bootstrap script pointing to http://openui5.hana.ondemand.com.
If I want to point the bootstrap to a local ui5 library then I just specify its resource root as another base option. All works good. 
If I want to use a proxy for an odata call for example then I use a middleware config in connect to do it. 

Now with the openui5-connect wrapper I can't seem to get it to work with the first case above. 
Based on your response it sounds like I would need to configure a proxy. But why does it work fine with connect on its own??

**Comment by matz3** [comment]
Can you post an example of what you are trying to do (Gruntfile.js)?
To have a generic proxy for your OData calls, you can use the `proxypath` option, see [here](https://github.com/SAP/grunt-openui5#proxypath).

**Comment by js1972** [comment]
Sorry this can be closed. It was actually issue #13 that was causing the issue. If I have the source files in the project root folder the grunt-openui5 module has issues.
