### ISSUE TITLE
Provide example openui5_preload grunt task when files are in root project folder. Strange issues...

### ISSUE THREAD

**Issue by js1972** [SAP/grunt-openui5#13]
Looking at https://github.com/SAP/openui5-sample-app the app resources are within a webapp directory. If I try to use the openui5-preload task in the projects root directory instead of a subdirectory like webapp it finds no resources.
Would it be possible to provide an example usage of the preload grunt task when resources are in the root folder?

I'm using the following in my gruntfile where dir.webapp is "." (current directory or root directory of project):

```
dir: {
	webapp: ".",
	dist: "dist",
	bower_components: "bower_components"
},

connect: {
	options: {
		port: 8080,
		hostname: "localhost",
		base: "."
	},
	src: {},
	dist: {}
},

openui5_connect: {
	//options: {
	//	resources: [
	//		"<%= dir.bower_components %>/openui5-sap.ui.core/resources",
	//		"<%= dir.bower_components %>/openui5-sap.m/resources",
	//		"<%= dir.bower_components %>/openui5-themelib_sap_bluecrystal/resources"
	//	]
	//},
	src: {
		options: {
			appresources: "<%= dir.webapp %>"
		}
	},
	dist: {
		options: {
			appresources: "<%= dir.dist %>"
		}
	}
},

openui5_preload: {
	component: {
		options: {
			resources: {
				cwd: "<%= dir.webapp %>",
				prefix: "todo"
			},
			dest: "<%= dir.dist %>"
		},
		components: true
	}
},
```
If I remove ```prefix: "todo"``` it actually outputs some info to the screen but says 0 files added. With the prefix in it outputs and does nothing...

Note also in the connect task above that I had to put ``` base: "." ``` to get it to allow access to the ui5 library when testing with ```https://openui5.hana.ondemand.com/resources/sap-ui-core.js```

**Comment by js1972** [comment]
Project structure...
![image](https://cloud.githubusercontent.com/assets/1317161/5930422/69f50c9c-a6ca-11e4-93e9-ae19256329c7.png)

**Comment by matz3** [comment]
What is your use case to have your app in the root directory?

If you configure the preload task to use the root directory it will scan all the files (including node_modules / bower_components / dist) and add them to the Component-preload.js file.
I guess that's the reason why it takes so long and does not produce any output.
You can configure the `src` option in the `resources` map to exclude those folders, but I don't think that using the root directory for the app sources is a good practice.

**Comment by js1972** [comment]
The only reason I use the root directory to contain my index.html and component.js or app.js is that it does seem to be the common (and maybe even best) practice. 
The WebIDE for example places these files in the project root. The widely used html boilerplate project which is the basis for a huge amount of websites does this. The yeoman web app generator also does this. So if anything it would see that placing these files in the project root is the best practice. In fact the one tool that I've seen push resources down into a webapp folder in recent times in eclipse. 
Practically speaking however it makes no difference at all - just convention. 
I'll have a play around with using the resources file settings to ignore all files except *.js in the root folder and see how it goes. 
Think of this use case which I think will be common (for me at least):1. Bootstrap a new project in WebIDE 2. Git clone it to local machine for continued development3. Add build tools with bower, grunt and so on and use the grunt-openui5 module. 
Now I can have live reloading and linting as I code and the ability to generate preload files for the final build.  ;-)

Thx. 






On Fri, Feb 6, 2015 at 2:14 AM -0800, "Matthias Oßwald" <notifications@github.com> wrote:












What is your use case to have your app in the root directory?



If you configure the preload task to use the root directory it will scan all the files (including node_modules / bower_components / dist) and add them to the Component-preload.js file.

I guess that's the reason why it takes so long and does not produce any output.

You can configure the src option in the resources map to exclude those folders, but I don't think that using the root directory for the app sources is a good practice.
