### ISSUE TITLE
Unable to get openui5_connect task to serve my app with resources in the root folder

### ISSUE THREAD

**Issue by js1972** [SAP/grunt-openui5#14]
This is closely related to issue #13 which you closed. If you see my final comment on that issue you'll see that I believe it is more widely used to have resources in the root folder than in a webapp folder.

When using the root folder the openui5_connect task won't serve the resources straight away - there is a long delay of a couple of minutes before it works. Any refresh takes equally long.

I have excluded some of the folders like so (to try and ensure its not scanning them for some reason?):
```
src: {
	options: {
		appresources: [
			"!./node_modules",
			"!./model",
			"!./bower_components",
			"<%= dir.webapp %>"
		]
	}
},
```

When I use the grunt-contrib-connect module on its own this all works perfectly well.

```
connect: {
	options: {
		port: "<%= localServerPort %>",
		livereload: 35729,
		hostname: "localhost",
		base: "."
	},

	// Must have at least one connect task!
	livereload: {
	}
```

**Comment by matz3** [comment]
`appresources` (as well as `resources` and `testresources`) are defined to only include folders, not exclude. All defined folders will be registered using [serve-static](https://github.com/expressjs/serve-static) which currently doesn't support exclusions, see https://github.com/expressjs/serve-static/issues/8 (however this could be fixed using custom middleware).

I just tried this out with the [openui5-sample-app](https://github.com/SAP/openui5-sample-app).
The only thing I changed was to move all files from `webapp` into the root folder and adopting `dir.webapp` to `.` in `Gruntfile.js`.

For me it was working fine with `grunt serve` (openui5_connect task) and `grunt connect:src:keepalive` (grunt-contrib-connect task). But I guess the performance is related to the hardware. Can you provide some details about your use case and how to reproduce it?

**Comment by js1972** [comment]
I'll investigate again tomorrow. Performance when running in the webapp folder is instant. 






On Tue, Feb 10, 2015 at 1:11 AM -0800, "Matthias Oßwald" <notifications@github.com> wrote:












appresources (as well as resources and testresources) are defined to only include folders, not exclude. All defined folders will be registered using serve-static which currently doesn't support exclusions, see expressjs/serve-static#8 (however this could be fixed using custom middleware).



I just tried this out with the openui5-sample-app.

The only thing I changed was to move all files from webapp into the root folder and adopting dir.webapp to . in Gruntfile.js.



For me it was working fine with grunt serve (openui5_connect task) and grunt connect:src:keepalive (grunt-contrib-connect task). But I guess the performance is related to the hardware. Can you provide some details about your use case and how to reproduce it?

**Comment by js1972** [comment]
I've added a watch task as well so that I can have live-reloading of the browser on changes... My stupid mistake was that when I changed dir.webapp to "." it meant that it was also watching there which included everything in npm_modules and so on. Fixed the watch task and all is good. Thankyou!
