### ISSUE TITLE
Changes made by Visual Editor for Fiori Elements not included in dist folder.

### ISSUE THREAD

**Issue by leowll** [SAP/grunt-openui5#149]
Created Fiori Elements project using WebIDE Full Stack and changed the table using Visual Editor to support "export to excel".
These kind of changes will not be included into the build result "dist" folder.
Is there any configuration missing ?  or just Grunt build does not support Visual Editor changes?

**Comment by matz3** [comment]
This might be related to the flexibility changes, which need to be bundled.
The grunt tasks do not support this step, but the UI5 Tooling does:
https://sap.github.io/ui5-tooling/

See:
https://github.com/SAP/ui5-builder/blob/master/CHANGELOG.md
https://github.com/SAP/ui5-builder/issues/353

Currently there are no new features planned for this project.
