### ISSUE TITLE
openui5_connect task not working with grunt-contrib-connect 0.11.*

### ISSUE THREAD

**Issue by sachebotarev** [SAP/grunt-openui5#15]
Example:
In application https://github.com/SAP/openui5-sample-app I changed Gruntfile.js  and I have  error.
see attachment 
![d__desktop_openui5-sample-app-master - far 3 0 4401 x64 2015-08-06 15 45 54](https://cloud.githubusercontent.com/assets/344731/9111723/636e05fe-3c52-11e5-9c5f-c02caad41708.png)

**Comment by matz3** [comment]
Fixed with `0.8.0` which just got published.
