### ISSUE TITLE
Add mangle option

### ISSUE THREAD

**Issue by jvail** [SAP/grunt-openui5#17]
As far as I understand the code is also mangled by default. Is it possible to add options.mangle true|false and pass it to UglifyJS?
https://github.com/SAP/grunt-openui5/blob/master/tasks/preload.js#L210

**Comment by matz3** [comment]
> As far as I understand the code is also mangled by default.

Correct. This is the default of UglifyJS2.

> Is it possible to add options.mangle true|false and pass it to UglifyJS?

In general I think it should be allowed to configure such things.

But I'm not sure if it would be good to just add a `mangle` option.
It might make more sense to add a generic way to customize the `compress` process in general. Maybe even something which also works for other file types (xml, json, ...).

@petermuessig @codeworrior what do you think?

**Comment by matz3** [comment]
In #40 there is another requirement to provide an option to UglifyJS.
So I guess it makes sense to implement a generic solution as already suggested.

I could think of something like this

```js
grunt.initConfig({
  openui5_preload: {
    component: {
      options: {
        resources: {
          cwd: 'webapp',
          prefix: 'my/app'
        },
        dest: 'dist',

        // "true" to activate with default options (current behavior)
        // specify object for additional options
        compress: {
          uglifyjs: {
            "mangle": false, // as requested in #17
            "output": {
              "ascii_only": true // as requested in #40
            }
          }
        }
      },
      components: 'my/app'
    }
  }
});
```

The provided options would be passed to UglifyJS after always overriding `fromString` (as this is required) and optionally overriding `output. comments` (if not defined in options).

@jvail @yaruson

**Comment by matz3** [comment]
This is now possible by providing uglifyjs options like described in the code sample above.
README docs update and release will be done soon.
