### ISSUE TITLE
Generated Component-preload.js is not JSHint & JSCS valid

### ISSUE THREAD

**Issue by agraebe** [SAP/grunt-openui5#19]
Hi,

I wanted to submit a new [Todo MVC](todomvc.com) example app for OpenUI5 and I included a Component-preload.js file to it. [During testing](https://travis-ci.org/tastejs/todomvc/builds/99756267), I realized that the produced code is not following their (quite strict) JSCS and JSHint rules:
- disallowQuotedKeysInObject = true
- validateQuoteMarks = single
- maximumLineLength = 120

Could we get an option to control the style of the output of the ```openui5_preload``` task?

**Comment by agraebe** [comment]
Actually, never mind.. The purpose of uglify is obvisouly to shorten the size of the output file, so following the exposed rules would be nonsense ;) 

I figured I could just ignore the output file ``Component-preload.js`` using the configuration files like outlined below:

## .jscsrc
```
{
	"excludeFiles": ["js/Component-preload.js"]
}
```

## .jshintignore
```
js/Component-preload.js
```

**Comment by matz3** [comment]
Exactly. As long as Uglify creates valid JavaScript it would only make sense to lint the source files so includes / excludes are fine.
