### ISSUE TITLE
Exclude Component-preload.js from SRC

### ISSUE THREAD

**Issue by agraebe** [SAP/grunt-openui5#21]
It looks like the openui5_preload task by deafuly includes "Component-preload.js" files. Hence, with multiple executions fo the same task, the previous preload will always be appended and the file become bigger and bigger.

Is there a way to specifically exclude existing preload files from the SRC? I think this should also be a default

**Comment by matz3** [comment]
That's right and I already thought about excluding it by default. As there should never be a case where it is intended to include the preload into the same file again I think it is save to change that.

In the meantime you can define an exclude in your configuration:
(I just saw that the [readme example](https://github.com/SAP/grunt-openui5#object) is not correct as excludes need to start with an exclamation mark. I will fix that)
```
webapp
  - Component.js ("my.app.Component")
Gruntfile.js
```
```js
openui5_preload: {
	component: {
		options: {
			resources: {
				cwd: "webapp",
				prefix: "my/app"
			},
			dest: "webapp"
		},
		components: {
			"my/app": {
				// note that defining the "src" property overwrites all default includes/excludes
				src: [
					"my/app/**", // include all available resources (this is the default)
					"!my/app/Component-preload.js" // exclude the Component-preload.js
				]
			}
		}
	}
}
```

**Comment by agraebe** [comment]
Sweet, I'll check it out as well. In the meantime, I have updated the readme in this PR: https://github.com/SAP/grunt-openui5/pull/22

**Comment by matz3** [comment]
Thanks :+1: I've added some comments.
