### ISSUE TITLE
Dependency "multiline" is deprecated

### ISSUE THREAD

**Issue by fwilhe** [SAP/grunt-openui5#234]
When installing this package I got this warning by npm

> npm WARN deprecated multiline@2.0.0: This was a fun hack, but now we have template literals, so use that instead.

The package in question is [this one](https://www.npmjs.com/package/multiline) which has not had a release in 4 years and is marked as deprecated. Is it possible to get rid of this dependency?

**Comment by matz3** [comment]
Sure, feel free to file a PR 👍🏻
