### ISSUE TITLE
Whitesource issues in @sap/grunt-sapui5-bestpractice-build

### ISSUE THREAD

**Issue by VijiSelvarajan** [SAP/grunt-openui5#255]
Whitesource issues are reported in latest version of @sap/grunt-sapui5-bestpractice-build - 1.4.15
High severity issues are reported in below packages which are part of @sap/grunt-sapui5-bestpractice-build - 1.4.15
uglify-js - 3.4.10
xmldom - 0.7.5
terser - 5.14.1
async-1.5.2

**Comment by matz3** [comment]
`@sap/grunt-sapui5-bestpractice-build` is not part of the UI5 Tooling project (our modules all start with @ui5/*).

Please open a support ticket via the [SAP Support Portal](https://support.sap.com/) for component `CA-WDE-BLD-GRUNT`.
