### ISSUE TITLE
generate source maps with less

### ISSUE THREAD

**Issue by davidtingsu** [SAP/grunt-openui5#26]
Hi, I was wondering if it is possible to autogenerate the sourcemaps so that it is possible to work in chrome with[ CSS preprocessors](https://developer.chrome.com/devtools/docs/css-preprocessors)

Currently, looking into [grunt-contrib-less](https://github.com/gruntjs/grunt-contrib-less), because that appears to be `less.Parser`

Looking into http://stackoverflow.com/a/25732523/1123985 but having trouble reproducing solution.

This would greatly speed up ui5 css development!

**Comment by matz3** [comment]
@davidtingsu sorry for the very late feedback to this issue. I wanted to have a deeper look into this a while ago but then had other priorities and forgot about it again.

I just had a very quick look into [grunt-contrib-less](https://github.com/gruntjs/grunt-contrib-less).
This plugin uses our own [less module](https://github.com/SAP/less-openui5) which would have to be extended as well to return the source maps created by less. But it doesn't sound to be too hard to implement in first place.

If someone wants to have a deeper look into this, please feel free to do so 👍 
Let me know if there is anything I can help with.

**Comment by matz3** [comment]
Closing for now as there was no response from someone else and we currently don't have any plans to add Source Maps for less/css.
