### ISSUE TITLE
openui5_preload adds sub components to "root" Component-preload.js

### ISSUE THREAD

**Issue by mkueng1** [SAP/grunt-openui5#28]
I have an app with a sub component:

```
app
|- Component.js
|- model
|...
|- shared
   |- Component.js
   |- model
   |...
```

When I build  the project with "components: true" the app/Component-preload.js contains all the resources including the ones from shared.
I would have expected that each component only provides its recources and not the ones of sub components. Or is this intentionally?

**Comment by matz3** [comment]
Yes, this is intentionally.

You can configure what should be included in the preload using the `[src](https://github.com/SAP/grunt-openui5#src-1)` option:

```js
components: {
  "app": {
    "src": [
      "app/**", // this is the default
      "!app/shared/**" // excludes the embedded component
    ]
  }
}
```

**Comment by mkueng1** [comment]
I already tried that. The exclusion also applies when the sub component preload is built - so the sub component is not built.

**Comment by matz3** [comment]
There are two different places where such filters can be set:

1. On `resources` level (see [here](https://github.com/SAP/grunt-openui5#src)). This is to collect all relevant files (e.g. filtered by type) regardless of libraries/components.
2. On `components` / `libraries` level (see [here](https://github.com/SAP/grunt-openui5#src-1)). Here you can define filters for a specific preload bundle

To build the two components individually the following config should be correct:
```js
components: {
  "app": {
    "src": [
      "app/**", // this is the default
      "!app/shared/**" // excludes the embedded component
    ]
  },
  "app/shared": {} // use default "src" filter ("app/shared/**")
}

**Comment by mkueng1** [comment]
Thanks for your workaround. This works.
Still, for me it is an issue that with components:true sub modules are included in the "root" Component-preload.js. One of the goals beneath structuring is to only lazy load large parts of an application.
In my opinion when components:true is set the resources covered by sub components shouldn't appear in the in the "root" Component-preload.js.

**Comment by matz3** [comment]
Alright. As it's still possible to provide the more complex configuration (`src` option) I would be fine with changing the default behavior as suggested. PR welcome.

**Comment by matz3** [comment]
This project has been deprecated (see https://github.com/SAP/grunt-openui5/pull/283)
