### ISSUE TITLE
support for data-sap-ui-theme-roots bootstrap parameter?

### ISSUE THREAD

**Issue by citoki** [SAP/grunt-openui5#29]
Would it be worth to support another import parameter in **openui5_connect** task for custom themes? Like it's done for other resource paths, e.g. 'appresources', 'resources' and 'test-resources'. 

In the [theme designer help](https://help.hana.ondemand.com/theme_designer/frameset.htm?64db0a0fda9645e1ab64d1787318bb04.html), there is a parameter for setting themes via bootstrap configuration: ``data-sap-ui-theme-roots``. In the WebIDE is this done via a separate route entry in neo-app.json file. For local development this file is not respected in ``openui5_connect`` task. It could be done in a separate middleware by the consumer of this grunt task, but for convenience reason I'd like to create a pull request with an dedicated parameter.

Any thoughts on this?

--
Steffen

**Comment by matz3** [comment]
Feel free to suggest how the new parameter should behave.

The current routing looks like this
- `appresources` :arrow_right:  `/`
- `resources` :arrow_right: `/resources`
- `testresources` :arrow_right: `/test-resources`

So in case you configured a `themeroot` for your theme you might put it in `appresources` as it doesn't add a path prefix.
If it's not configured the theme will be loaded from `/resources/<library-namespace>/themes/<theme-name>/` so you should be able to configure an additional `resources` path.

**Comment by citoki** [comment]
Thanks for your input, it's working fine after exporting custom theme from Theme Designer and copy it to the root folder. Adjusting the ``appresources`` parameter with an array of folders which are served on application root level was the only step which is needed, to get it running.

Gruntfile.js
```js
appresources: ["webapp", "tdexport"],
```

Sample config for UI5 bootstrap
```js
data-sap-ui-theme="customTheme"
data-sap-ui-theme-roots='{"customTheme" : "/tdexport/customTheme1/UI5/"}'
```
