### ISSUE TITLE
Is there a grunt command to create the exact SDK downloaded package ?

### ISSUE THREAD

**Issue by RobertoMalatesta** [SAP/grunt-openui5#38]
Hi,

I just started to use the grunt tools to create my custom build package so forgive my ignorance.

After the documented **grunt build** I would expect a complete **resources** tree, containing a **sap-ui-core.js** and a tree structure equivalent to the ready-to-run downloaded package.

Is there a command to achieve that?

Thanks for all the good code,

Roberto

**Comment by matz3** [comment]
I guess you are referring to the [`grunt build` task](https://github.com/SAP/openui5/blob/master/docs/tools.md#build) of the OpenUI5 project.

It currently creates a build package *similar* to the one you can download from http://openui5.org.
There should be a **resources** folder containing all the relevant files (including a **sap-ui-core.js**).
Please also see our [packaged repositories](https://github.com/openui5?query=packaged-) which are containing the build results from the OpenUI5 project (using `grunt build`)

It is only *similar* as it uses the Open Source modules (like this grunt plugin) to build OpenUI5 while the ready-to-run package you can download is built with our internal tools.
We are working on a publicly available way to run a build for OpenUI5 that produces the exact same package as you can already download, but we are not there, yet.

I hope this answers your questions.

**Comment by RobertoMalatesta** [comment]
Thanks @matz3 for the super-fast reply.

Since I'm heavily modifying some components, I'd like know a way to consume my customized build in a quick way, changing the classical:
`
 <script src="https://openui5.hana.ondemand.com/resources/sap-ui-core.js"... 
`
into something else.

A sub-optimized solution will do while waiting for the official script.

--R

**Comment by matz3** [comment]
Did you check out the [`grunt build` task](https://github.com/SAP/openui5/blob/master/docs/tools.md#build) in the OpenUI5 repo?
You should be able to locally build the project and run your app with it.

Just let me know if you have any specific questions.

**Comment by RobertoMalatesta** [comment]
Yep. That's where I started from.
the problem is how to use the libraries.
Today I successfuly use this code to bootstrap a pre-built Openui5 SDK:
`
  <script
     src="/ui5/1.38.3/resources/sap-ui-core.js"
    id="sap-ui-bootstrap" data-sap-ui-libs="sap.tnt, sap.m, sap.ui.table, sap.ui.commons"
    data-sap-ui-theme="sap_bluecrystal">
    </script>
`
(the same works pointing the CDN).

But, after a complete build with grunt the tree structure of the directories is not the same.
In particular, the resources directory containing the sap-ui-core.js does not contains the  libs as well, so the following code will not work:

`
    <script 
      src="openui5_custom/openui5/target/openui5-sap.ui.core/resources/sap-ui-core.js"
      id="sap-ui-bootstrap" data-sap-ui-libs="sap.tnt, sap.m, sap.ui.table, sap.ui.commons"
      data-sap-ui-theme="sap_bluecrystal">
    </script>
`
 
Do I have to change the data-sap-ui-libs references to the libraries, will it work, or is there another build command that do some deployment into a different directory?

Thank you

--R

**Comment by matz3** [comment]
> Do I have to change the data-sap-ui-libs references to the libraries, will it work, or is there another build command that do some deployment into a different directory?

You could configure the [`resourceRoots`](https://openui5.hana.ondemand.com/#docs/guide/91f2d03b6f4d1014b6dd926db0e91070.html) to point to the other directories of the libraries. But that's not really handy in case you would like to just change the `src` to switch from CDN to local.

There is currently only a [`compress` task](https://github.com/SAP/openui5/blob/15b5fde00cc7bb956fd3d9ca7bf7bd0ff1616bea/grunt/config/compress.js) configured to package all libraries into one ZIP file, but I guess that's also not an option.

So I could think of another `copy` task to copy all the libraries into `target/openui5` which one could use to serve a local UI5 build as drop-in replacement for the CDN version like this:
```html
<script id="sap-ui-bootstrap"
    src="openui5_custom/openui5/target/openui5/resources/sap-ui-core.js">
</script>
```

**Comment by matz3** [comment]
You can, of course, also just use the local development server via [`grunt serve`](https://github.com/SAP/openui5/blob/master/docs/tools.md#serve) in case you would like to make changes to OpenUI5 and directly test it within your app without even trigger a build step.

**Comment by RobertoMalatesta** [comment]
Thanks @matz3 for the great support.

> You can, of course, also just use the local development server via grunt serve in case you would like to make changes to OpenUI5 and directly test it within your app without even trigger a build step.

I've done this while editing the components and it worked fine.
But then I have to replace the standard CDN lib with my custom one on my Apache Web Server.
Continue using grunt serve is not an option in production.

> You could configure the resourceRoots to point to the other directories of the libraries. But that's not really handy in case you would like to just change the src to switch from CDN to local.

This seems a lot of work and somewhere a message a message popped out on the console log telling me it was somehow deprecated. I could remember wrongly since I did a short quick attempt (lack of time).

> So I could think of another copy task to copy all the libraries into target/openui5 which one could use to serve a local UI5 build as drop-in replacement for the CDN version like this:

I think this is the most required element in the whole building system as of today (everything else works great).

As an alternative I will have a look at the grunt build generated structure and assemble them with a bash script (again, it's time that's missing).



--R

**Comment by matz3** [comment]
> But then I have to replace the standard CDN lib with my custom one on my Apache Web Server.
Continue using grunt serve is not an option in production.

Sure. It is not intended to be used for production.

I will push a change soon to provide a `bundle` task you can run after running `grunt build`, e.g. like this:
```shell
grunt build bundle
```
It will take a bit more time than expected as the resources are copied twice, but I didn't want to change the build task as a whole. And as it is only required for production you shouldn't have the need to run it too frequently.

**Comment by RobertoMalatesta** [comment]
That will be super, thanks.

--R

**Comment by matz3** [comment]
The change is now pushed: https://github.com/SAP/openui5/commit/d605c3635acc2f9c9ef7ed39720d6c164d9e5de7
