### ISSUE TITLE
Minification issue

### ISSUE THREAD

**Issue by yaruson** [SAP/grunt-openui5#39]
Hello, I'd like to suggest adding `ascii_only: true` to preload task of this plugin. The reason is that after minification escaped national symbols are converted back into plain.

This issue has been discussed in [relevant UglifyJS](https://github.com/mishoo/UglifyJS2/issues/490) issue.

**Comment by matz3** [comment]
I would rather see this the same way as in #17.
There should be a generic way to provide options to UglifyJS.
I'm closing this in favor of #17. Please see my comments there.
