### ISSUE TITLE
component preload does not include manifest.json

### ISSUE THREAD

**Issue by DirkSW** [SAP/grunt-openui5#46]
Hi
 we are using the manifest.json within UI5 components.
Is it possible to include this in defaultResourcePatterns.
Or do we need to explicit do this in grunt command ?

thanks & regards,
Dirk

**Comment by matz3** [comment]
For now you can just explicitly include it in your configuration but it actually makes sense to include it by default.

I guess it should not be part of the [`defaultResourcePatterns`](https://github.com/SAP/grunt-openui5/blob/077af46e2b63e128003a93b5cae295b0aa8d30b6/tasks/preload.js#L23-L32) but rather explicitly included from the same path as the `library.js` / `Component.js` file.

**Comment by mathiseelan02** [comment]
@matz3 is there any update? to add component-preload in manifest.json?

**Comment by matz3** [comment]
@mathiseelan02 in the meanwhile we've published the [UI5 Tooling](https://github.com/SAP/ui5-tooling) as a successor of this grunt tasks. There, the component preloads include the manifest.json by default (see [ui5-builder module](https://github.com/SAP/ui5-builder)).

Therefore closing this issue.

**Comment by matz3** [comment]
The caching behavior is depending on your server, so I guess I'm unable to help here.

> So is there is a way to explicitly include component-preload, similar to manifestUrl in configuration.

What do you mean with that? Including the component-preload into what?

**Comment by mathiseelan02** [comment]
Currently, the component-preload file loaded from ui5loader-dbg.js is there a way to load it externally?
