### ISSUE TITLE
library-preload extension

### ISSUE THREAD

**Issue by rlindner81** [SAP/grunt-openui5#48]
I found a very minor but curious problem. Your preload task for building a library produces the file
`library-preload.json`. But OpenUI5 appears to expect `library-preload.js` and only does a fallback to `.json`, if that file is not found.
```
failed to load Javascript resource: xxx/lib/library-preload.js
failed to load 'xxx/lib/library-preload.js' (undefined), falling back to library-preload.json
```

It would be super-easy to add the target extension as an option. Would you consider this, or is it a conscious decision to go with `.json` and OpenUI5 will not expect `.js` at some point?

**Comment by matz3** [comment]
See #45 / #47.
We will soon do a new release.
