### ISSUE TITLE
Getting error "No files Found"

### ISSUE THREAD

**Issue by nitinsinghit** [SAP/grunt-openui5#54]
Hi Guys,

I am not able to figure this out why I am keep getting this error
"Warning: No files found. Check your "resources" option! Use --force to continue." I have correct file structure

**Comment by matz3** [comment]
You are using the `openui5_preload` task, right?
It does not make use of [grunt's default way to define files](https://gruntjs.com/configuring-tasks#files), but loads the files on its own as described [here](https://github.com/SAP/grunt-openui5#resources).

Please checkout [the examples](https://github.com/SAP/grunt-openui5#usage-examples-1).

Hope this helps, otherwise please share your config 👍

**Comment by nitinsinghit** [comment]
'use strict';
module.exports = function(grunt) {

    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

         openui5_preload: {
            component: {
                options: {
                    resources: {
                        cwd: 'webapp',
                        prefix: 'my/app',
                        expand: true,
                        src: [
                            'webapp/controller/*.controller.js',
                            'webapp/view/*.fragment.xml',
                            'webapp/model/*.json',
                            'webapp/model/*.js',
                            'webapp/view/*.view.xml'
                        ]
                    },
                    dest: 'dist',
                    compress: true
                },
                components: true
            }
        },
        connect: {
            server: {
                options: {
                    port: 8001,
                    base: '.'
                }
            }
        }
      

    });

// These plugins provide necessary tasks.
    grunt.loadNpmTasks('grunt-openui5');
    grunt.loadNpmTasks('grunt-contrib-connect');
    
    // By default, lint and run all tests.
    grunt.registerTask('default', [,'openui5_preload']);


};

**Comment by matz3** [comment]
@nitinsinghit as you are defining `cwd: 'webapp'` you need to strip off the `webapp` folder from the patterns defined in `src`.

```js
resources: {
  cwd: 'webapp',
  prefix: 'my/app',
  expand: true,
  src: [
    'controller/*.controller.js',
    'view/*.fragment.xml',
    'model/*.json',
    'model/*.js',
    'view/*.view.xml'
  ]
}
```

**Comment by nitinsinghit** [comment]
@matz3  after you suggestion this is my config for preload and I am still getting error -

>  Warning: No files found. Check your "resources" option! Use --force to continue.

> openui5_preload: {
>             component: {
>                 options: {
>                     resources: {
>                         cwd: 'webapp',
>                         prefix: 'my/app',
>                         expand: true,
>                         src: [
>                             'controller/*.controller.js',
>                             'view/*.fragment.xml',
>                             'model/*.json',
>                             'model/*.js',
>                             'view/*.view.xml'
>                         ]
>                     },
>                     dest: 'dist',
>                     compress: true
>                 },
>                 components: true
>             }
>         }

**Comment by matz3** [comment]
Could you please share your project's file structure?

**Comment by nitinsinghit** [comment]
![projectstructure](https://cloud.githubusercontent.com/assets/545884/24156121/15c0ff66-0e2c-11e7-83a5-0f9b5c10d32a.PNG)

**Comment by matz3** [comment]
Well, in your case the `Gruntfile.js` (which serves as your starting point for the relative paths) is already within the `webapp` folder (which I would not recommend).
Better move those files like `Gruntfile.js`, `package.json`, `.gitignore`, `.eslintrc`, `README.md`, ... one level up to the repository root as those are not part of the app and not needed at runtime.
But to just fix your configuration you would need to change the `cwd` to `./`.

**Comment by nitinsinghit** [comment]
Got it. Thanks. 
Now I am seeing this new error - `Warning: No preload type specified. Please provide "components" and/or "libraries" in task target object! Use --force to continue.`
