### ISSUE TITLE
Incorrect module names in library-preload.json when folder(git project) has '.' symbol 

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/grunt-openui5#59]
Dear developers,

Here is an issue we faced recently.

We created a library. Name of git project + directory after clone is booking.ovp

Inside we created a library with nested modules.

However after build with grunt we have code like this:

`{
	"version": "2.0",
	"name": "booking.ovp.library-preload",
	"modules": {
		"booking.ovp/cards/charts/donut/Component.js": "sap.ui.define(`

But in fact booking.ovp is a library name which means we expect to have modules like this in the file:
`
"booking/ovp/...`

We fixed this problem by a small adjustement of preload.js:

Instead of this:
`preloadObject.modules[preloadFile] = fileContent;`

we set this:
`preloadObject.modules[preloadFile.replace(/[.](?=.*[.])/, '/')] = fileContent;`

In this case if folder name is a.b.c we'll have a/b/c path for modules.

How do you think can it be a standard solution?

Thanks!

**Comment by ThePlenkov** [comment]
Closed with comment here https://github.com/SAP/grunt-openui5/pull/60

**Comment by matz3** [comment]
Hey @ThePlenkov,
I'm sorry that there was no direct response - but your solution mentioned in the PR comment is exactly what I would suggest as well.

**Comment by ThePlenkov** [comment]
@matz3 Thank you. However this change finally didn't work. If I call module like booking/ovp - npm starts working incorrect. They don't let us / symbol in the package name.

I solved my problem finally with own grunt module: https://www.npmjs.com/package/grunt-sapui5
