### ISSUE TITLE
Pure programatic APIs & Decoupling from grunt.

### ISSUE THREAD

**Issue by bd82** [SAP/grunt-openui5#61]
Related to https://github.com/SAP/grunt-openui5/issues/20

Are there any plans to provide plain node.js programatic APIs for OpenUI5 dev flows?

That will enable supporting any build system and avoids coupling the development flows to a build system that is becoming less and less popular and common...

See:
- https://stateofjs.com/2016/buildtools/
  * That is from 2016, the 2017 survey results should hopefully be released soon.
- http://www.npmtrends.com/grunt-vs-gulp

Just to emphasize I'm not saying there should be gulp or webpack plugins for Openui5 dev flows.
Instead there should be generic APIs which could be reused in **any** javaScript build tool.

Thanks.
Shahar.

**Comment by RandomByte** [comment]
Hi @bd82,

Yes, this is actually what we are working on right now.

At the last [UI5con](http://openui5.org/ui5con/material.html) there have been two talks mentioning and sharing some of our plans regarding the "evolution" build tooling:
- UI5 Evolution – performance, architecture, trends: https://youtu.be/vZfxBXu6_Lc?t=13m49s
- CI – Build process & automated testing of UI5 Apps: https://youtu.be/TceM3zf8VSk?t=28m4s

Hope this answers your question!
Merlin

**Comment by bd82** [comment]
Thanks @RandomByte for the detailed information!

**Comment by RandomByte** [comment]
The "new" UI5 Build and Development Tooling has been released as a pre-alpha: https://github.com/SAP/ui5-tooling
