### ISSUE TITLE
Can bundling be done for random resources (without component.js)?

### ISSUE THREAD

**Issue by gadisn** [SAP/grunt-openui5#62]
Hi,

I have several UI5 resources I would like to bundle (a view, a controller and custom controls).
They are not defined by a component.js file.

Can such resources be bundled using openui5_preload, or does it only support library and/or component?

Thanks

**Comment by matz3** [comment]
Right now we only support Components / Libraries to be bundled with the grunt task, as it covers the main use cases. But we have this on our list.
Technically it's possible to bundle any kind of resources as part of a preload bundle and load them.
You can take [this gist](https://gist.github.com/matz3/521ab104c48ca24c389d) as a starting point. Please note that the bundles use internal API which might change in future.

Hope this helps 👍

**Comment by matz3** [comment]
Closing as there was no further feedback within a year.
