### ISSUE TITLE
Headline for compatVersion sould be on level h4

### ISSUE THREAD

**Issue by SteffenGa** [SAP/grunt-openui5#67]
In the README.md documentation, the headline level of "compatVersion" (https://github.com/SAP/grunt-openui5#compatversion) should be h4 (instead of h5), because it is a property under "options" (and not "resources") - technically proofed via trial & error in my Gruntfile ;)

**Comment by RandomByte** [comment]
Hi @SteffenGa

Thanks for that! Fixed with #68
