### ISSUE TITLE
Cors settings are being ignored?

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SAP/grunt-openui5#72]
Hello everyone, 

i tried to allow corse for our local development environment using this snippet:

```
cors: {
  origin: '*'
}
```
But it doesnt't show any reaction. Do i have to specify this option for `openui5_connect` or for:

```
    grunt.initConfig({
        connect: {
            options: {
                port: 8080,
                hostname: '*'
                // add corse support here?
           },
        },
```

can someone give me a hint how it should be used to allow external uses in my local environment?
I also tried adding a middleware and print some test messages, but these area also being ignored:

```
      middleware: function(connect, options, middlewares) {
        middlewares.unshift(function(req, res, next) {
          console.log("Test unshift");
          res.setHeader('Access-Control-Allow-Origin', '');
          res.setHeader('Access-Control-Allow-Methods', '');
          next();
        });
        middlewares.push(function(req, res, next) {
          console.log("Test push");
          // after openui5 middleware
        });
        return middlewares;
      }
```

It looks like this is being iggnored in favor of `openui5_connect` - so how do  i add support? or must i enable it in the browser...?

**Comment by matz3** [comment]
As it is a feature of the openui5 connect task, the option needs to be specified for `openui5_connect`, not `connect`.

```js
grunt.initConfig({

  openui5_connect: {
    options: {
      cors: {
        origin: '*'
      }
    }
  }

});
```

**Comment by matz3** [comment]
The CORS headers need to be set by the Server to where the request is sent.
This means that all files served by the connect / openui5_connect server can be loaded from different domains, but it doesn't mean that a website served from this server can sent request to any other domain (e.g. a backend).
So it seems in your case the backend needs to set the CORS headers.
Yes, a proxy can also be used to workaround this limitation.

**Comment by Gong-Bao-Chicken** [comment]
Where would i look for headers sent by the sap system and allow requests from my network? Specifically the ODATA Service. 🐉 

The alternative would proably be to integrate something like https://github.com/Rob--W/cors-anywhere into the grunt task and set the proxypath i guess?

**Comment by matz3** [comment]
Sorry, I can't provide any help regarding configuration of SAP systems.

You might checkout this proxy: https://github.com/chimurai/http-proxy-middleware
It can be integrated as grunt-connect middleware (see [here](https://github.com/gruntjs/grunt-contrib-connect#middleware)).

**Comment by Gong-Bao-Chicken** [comment]
to bad :-( . Thanks for the help anyway. I will check out your suggestion for a possible solution...
