### ISSUE TITLE
NPM warn security issue

### ISSUE THREAD

**Issue by gaiawork** [SAP/grunt-openui5#73]
Hi,

When using grunt-openui5 dependency, a security issue raised:
npm WARN notice [SECURITY] mime has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.2.11 - Run npm i npm@latest -g to upgrade your npm version, and then npm audit to get more info.

The problematic mime version is used from less-openui5 dependency.
I have opened an issue also to less-openui5: https://github.com/SAP/less-openui5/issues/25
Once it is fixed, grunt-openui5 should be updated to

Thanks,
Gaia

**Comment by matz3** [comment]
Please see my comment: https://github.com/SAP/less-openui5/issues/25#issuecomment-390175967
