### ISSUE TITLE
SAPUI5 requires files, which are already bundled into Component-preload.js

### ISSUE THREAD

**Issue by pubmikeb** [SAP/grunt-openui5#79]
I've built a `Component-preload.js` by `grunt-openui5@0.14.0` with `compatVersion: "1.44"` parameter since my SAPUI5 Core is 1.44.

The script:

    openui5_preload: {
    
    	component: {
    
    		options: {
    
    			resources: {
    
    				cwd: "<%= dir.webcontent %>",
    				prefix: "<%= dir.webapp %>/<%= dir.webcontent %>",
    				src: [
    					"**/*.js",
    					"**/*.html",
    					"**/*.json",
    					"**/*.fragment.html",
    					"**/*.fragment.xml",
    					"**/*.fragment.json",
    					"**/*.view.html",
    					"**/*.view.xml",
    					"**/*.view.json",
    					"**/*.properties",
    					"manifest.json",
    					"!test/**"
    				]
    			},
    			compatVersion: "1.44",
    
    			dest: "<%= dir.dist %>"
    		},
    
    		components: "<%= dir.webapp %>/<%= dir.webcontent %>"
    	}
    }

As the result, I have a file, which contains everything I mentioned in the script, I store it in `WebContent` folder, and update the paths according to the hierarchy, just like it is described in the SAPUI5 book.

When I test it, I get a strange behaviour — a browser loads both `Component-preload.js` and all the files, which are mentioned in it. In other words, after generation of the preloader browser downloads it, but ignores its content and still requests the separate files, although they are already located in this preloader,

I want that the files, mentioned in the preloader, will not be requested as separate files by the browser. Otherwise, there is no any reason to use preloader. How can I fix it?

P.S. The issue is similar to [Minified *.properties and *.css are still requested][1].

  [1]: https://github.com/SAP/grunt-openui5/issues/34

**Comment by matz3** [comment]
This sound's like a problem with the module namespace used when creating the Component-preload (see `prefix` option) and the actual module namespace that is used at runtime.
If there is a difference, the preloaded modules can't be taken from the preload cache and they are requested individually.

Can you share the content of your Component-preload.js?

**Comment by matz3** [comment]
Closing as there was not response for quite some time
