### ISSUE TITLE
Component-preload getting cached in browser

### ISSUE THREAD

**Issue by mathiseelan02** [SAP/grunt-openui5#81]
@matz3 - Currently component-preload file is cached in the browser, is there is a way to avoid this. Cant able to use cache-buster as we are using HANA.

So is there is a way to explicitly include component-preload, similar to **manifestUrl** in configuration.

**Comment by matz3** [comment]
The caching behavior is depending on your server, so I guess I'm unable to help here.

> So is there is a way to explicitly include component-preload, similar to manifestUrl in configuration.

What do you mean with that? Including the component-preload into what?

**Comment by mathiseelan02** [comment]
@matz3 Currently, the component-preload file loaded by ui5loader-dbg.js, is there a way to load it externally?

**Comment by mathiseelan02** [comment]
Yes via a script tag.

**Comment by matz3** [comment]
Well, in general this should be possible, as the component factory also just dynamically inserts a script tag to load the preload. The only problem might be that it could be loaded twice when the component factory is executed while the manually inserted script tag is still loading.

**Comment by mathiseelan02** [comment]
Currently for solving cache issue, loading the component preload from script tag again. Like you mentioned component preload file loaded twice. So its a waste request and time taken to load the script again.

Is there any way to solve this?

**Comment by matz3** [comment]
Usually this is solved by setting/implementing cache headers on the server to e.g. send conditional requests to check whether the resource has been modified instead of always caching the file for a period of time. This is specific to the server. Using the SAPUI5 cachebuster would be another option but that doesn't seem to be supported in your scenario.

**Comment by mathiseelan02** [comment]
@matz3 Thanks  👍 will try it.
